# **CSE Python Programming Lab — Practical 5**
**Topic:** List Slicing, Built-in List Functions, Advanced List Methods  
**Academic Associate:** Yesha Pandya  


This notebook contains the reference implementations for Practical Assignment 5.
Try working through the problem statements on your own first.
Use these cells as a guide if you get stuck or want to cross-check your logic and edge cases.

Make sure you understand the reasoning behind the syntax. You will need to explain your logic during lab evaluations and vivas.

## **Problem 1 (Easy)**
Given the list `numbers = [10, 20, 30, 40, 50, 60, 70]`, use basic list slicing `list[start:stop]` to extract and print the sub-list `[30, 40, 50]`.

In [1]:
numbers = [10, 20, 30, 40, 50, 60, 70]

# Index 2 holds value 30.
# We want up to value 50 (index 4), so the stop index must be 5 because stop_index is EXCLUSIVE.
sub_list = numbers[2:5]

print("Extracted sub-list:", sub_list)

Extracted sub-list: [30, 40, 50]


## **Problem 2 (Easy)**
Create a list `alphabet = ["a", "b", "c", "d", "e", "f", "g", "h"]`. Use slicing with a step value to print every second element starting from index 0.

In [2]:
alphabet = ["a", "b", "c", "d", "e", "f", "g", "h"]

# Slicing syntax: list[start : stop : step]
# Leaving start and stop empty defaults to beginning and end.
# Step value of 2 skips every second element.
every_second = alphabet[::2]

print("Every second element:", every_second)

Every second element: ['a', 'c', 'e', 'g']


## **Problem 3 (Easy)**
Given the list `data = [100, 200, 300, 400, 500]`, use slicing with a negative step `[::-1]` to create and print a reversed copy of the list.

In [3]:
data = [100, 200, 300, 400, 500]

# A step of -1 iterates backwards from end to start.
# This creates a brand new reversed copy without modifying the original list.
reversed_data = data[::-1]

print("Original list:", data)
print("Reversed copy:", reversed_data)

Original list: [100, 200, 300, 400, 500]
Reversed copy: [500, 400, 300, 200, 100]


## **Problem 4 (Easy)**
Given `scores = [88, 42, 95, 63, 71]`, write a program that uses the built-in functions `min()`, `max()`, and `sum()` to print the lowest score, highest score, and the total sum of all scores.

In [4]:
scores = [88, 42, 95, 63, 71]

# min() returns the smallest numerical element
lowest_score = min(scores)

# max() returns the largest numerical element
highest_score = max(scores)

# sum() calculates the running total of all items in an iterable
total_sum = sum(scores)

print("Lowest Score:", lowest_score)
print("Highest Score:", highest_score)
print("Total Sum:", total_sum)

Lowest Score: 42
Highest Score: 95
Total Sum: 359


## **Problem 5 (Easy)**
Create two lists: `team_a = ["Alice", "Bob"]` and `team_b = ["Charlie", "David"]`. Use the `.extend()` method to merge `team_b` into `team_a`. Print `team_a`.

In [5]:
team_a = ["Alice", "Bob"]
team_b = ["Charlie", "David"]

# .extend() iterates over its argument and appends each item to team_a IN-PLACE.
# (Unlike .append(), which would add team_b as a single nested list item)
team_a.extend(team_b)

print("Merged team_a:", team_a)

Merged team_a: ['Alice', 'Bob', 'Charlie', 'David']


## **Problem 6 (Easy)**
Create a list `votes = ["yes", "no", "yes", "yes", "no", "maybe"]`. Use the `.count()` method to find and print how many times `"yes"` appears in the list.

In [6]:
votes = ["yes", "no", "yes", "yes", "no", "maybe"]

# .count(value) calculates the exact number of occurrences of the given item
yes_count = votes.count("yes")

print("Number of 'yes' votes:", yes_count)

Number of 'yes' votes: 3


## **Problem 7 (Easy)**
Given `cities = ["Mumbai", "Delhi", "Bangalore", "Chennai"]`, use the `.index()` method to find and print the position (index number) of `"Bangalore"`.

In [7]:
cities = ["Mumbai", "Delhi", "Bangalore", "Chennai"]

# .index(value) returns the zero-based index of the first matching element
bangalore_position = cities.index("Bangalore")

print("Index position of Bangalore:", bangalore_position)

Index position of Bangalore: 2


## **Problem 8 (Easy)**
Create a list `prices = [450, 120, 890, 300, 50]`. Use the `.sort()` method to sort the list in ascending order (lowest to highest) and print it.

In [8]:
prices = [450, 120, 890, 300, 50]

# .sort() mutates the original list in-place in ascending order and returns None
prices.sort()

print("Ascending order prices:", prices)

Ascending order prices: [50, 120, 300, 450, 890]


## **Problem 9 (Moderate)**
Given `marks = [67, 89, 45, 92, 78]`, use `.sort(reverse=True)` to sort the list in descending order (highest to lowest) and print it.

In [9]:
marks = [67, 89, 45, 92, 78]

# Passing reverse=True modifies the in-place sorting order to descending
marks.sort(reverse=True)

print("Descending order marks:", marks)

Descending order marks: [92, 89, 78, 67, 45]


## **Problem 10 (Moderate)**
Create a list `original = [1, 2, 3]`. Use the `.copy()` method to create a duplicate named `shallow_copy`. Append `4` to `shallow_copy` and verify that `original` remains unchanged.

In [10]:
original = [1, 2, 3]

# .copy() creates a new independent list reference in memory
shallow_copy = original.copy()

# Modify only the copy
shallow_copy.append(4)

# Print both to prove original is untouched
print("Original list:", original)
print("Shallow copy list:", shallow_copy)

Original list: [1, 2, 3]
Shallow copy list: [1, 2, 3, 4]


## **Problem 11 (Moderate)**
Create a list `temp_logs = [24, 25, 26, 27]`. Use the `.clear()` method to remove all elements from the list. Print the list and its length (`len()`) to verify it is empty.

In [11]:
temp_logs = [24, 25, 26, 27]

# .clear() deletes all items inside the list in-place
temp_logs.clear()

print("Cleared list content:", temp_logs)
print("Length of list:", len(temp_logs))

Cleared list content: []
Length of list: 0


## **Problem 12 (Moderate)**
Given a list `matrix_row = [5, 10, 15, 20, 25, 30, 35, 40]`, use negative index slicing `[-4:]` to extract and print only the last 4 elements of the list.

In [12]:
matrix_row = [5, 10, 15, 20, 25, 30, 35, 40]

# Negative index -4 points to the 4th element from the end (25).
# Omitting the stop index tells Python to slice all the way to the end.
last_four = matrix_row[-4:]

print("Last 4 elements:", last_four)

Last 4 elements: [25, 30, 35, 40]


## **Problem 13 (Moderate)**
Write a program that takes a user-entered word and converts it into a list of characters. Check if the list is equal to its slice reverse (`lst == lst[::-1]`) to determine if the word is a Palindrome (e.g., `"radar"`). Print `True` or `False`.

In [13]:
user_word = input("Enter a word: ")

# Convert input word to lowercase and split into a list of characters
char_list = list(user_word.lower())

# A palindrome reads identically forward and backward
is_palindrome = (char_list == char_list[::-1])

print("Character List:", char_list)
print("Is Palindrome?", is_palindrome)

Enter a word: hahaahah
Character List: ['h', 'a', 'h', 'a', 'a', 'h', 'a', 'h']
Is Palindrome? True


## **Problem 14 (Moderate)**
Given `values = [12, 0, 45, 0, 78, 0, 90]`, write a program using a `while` loop and the `.remove()` method to delete all occurrences of `0` from the list. Print the cleaned list.

In [14]:
values = [12, 0, 45, 0, 78, 0, 90]

# .remove() only deletes the FIRST occurrence of a value it finds.
# We use a while loop to repeatedly check if 0 still exists in the list.
while 0 in values:
    values.remove(0)

print("Cleaned list without zeros:", values)

Cleaned list without zeros: [12, 45, 78, 90]


## **Problem 15 (Moderate)**
Create a list `items = ["pen", "notebook", "eraser"]`. Ask the user for an item name. Use an `if-else` statement paired with the `in` operator to check if it exists in the list. If it exists, print its index using `.index()`; if not, print `"Item not found"`.

In [15]:
items = ["pen", "notebook", "eraser"]
user_item = input("Enter item name to search: ").lower()

# Check existence first using 'in' operator to avoid ValueError during .index()
if user_item in items:
    found_index = items.index(user_item)
    print(f"Item '{user_item}' found at index {found_index}.")
else:
    print("Item not found")

Enter item name to search: notebook
Item 'notebook' found at index 1.


## **Problem 16 (Thinking-Based / Application)**
### **The Leaderboard Top-3 Filter**
You are designing the post-match summary for an esports tournament. The game engine generates an unsorted list of player scores: `all_scores = [340, 890, 120, 950, 670, 890, 410]`.
* Use the `.sort(reverse=True)` method to organize scores from highest to lowest.
* Use list slicing to extract only the top 3 highest scores.
* Calculate the average score of these top 3 players using `sum()` and `len()`.
* Print the top 3 scores list and their calculated average score.

In [16]:
all_scores = [340, 890, 120, 950, 670, 890, 410]

# 1. Sort the list descending in-place
all_scores.sort(reverse=True)

# 2. Extract top 3 elements via slicing (indices 0, 1, 2)
top_3_scores = all_scores[:3]

# 3. Calculate average using sum() and len()
average_top_3 = sum(top_3_scores) / len(top_3_scores)

# 4. Display results
print("Top 3 Scores:", top_3_scores)
print("Average of Top 3:", round(average_top_3, 2))

Top 3 Scores: [950, 890, 890]
Average of Top 3: 910.0


## **Problem 17 (Thinking-Based / Application)**
### **The E-Commerce Price Range Filter**
An online shopping platform allows users to apply a price filter. The system stores product prices in a list: `product_prices = [15, 80, 120, 45, 300, 210, 95, 50]`.
* Ask the user to input two numbers: `min_price` and `max_price`.
* Iterate through `product_prices` and create a new list `filtered_prices` containing only items that fall within `[min_price, max_price]` (inclusive).
* If no products match, print `"No items match your filter"`. Otherwise, print the sorted `filtered_prices` list using `.sort()`.

In [17]:
product_prices = [15, 80, 120, 45, 300, 210, 95, 50]

# Accept range boundaries from user
min_price = float(input("Enter minimum price: "))
max_price = float(input("Enter maximum price: "))

filtered_prices = []

# Filter prices within bounds (inclusive)
for price in product_prices:
    if min_price <= price <= max_price:
        filtered_prices.append(price)

# Check if any items matched criteria
if not filtered_prices:
    print("No items match your filter")
else:
    filtered_prices.sort()
    print("Matching products (sorted):", filtered_prices)

Enter minimum price: 234
Enter maximum price: 432
Matching products (sorted): [300]


## **Problem 18 (Thinking-Based / Application)**
### **The Playlist Re-orderer & Merger**
A user is merging two music playlists:
* `rock_playlist = ["Bohemian Rhapsody", "Hotel California"]`
* `pop_playlist = ["Shape of You", "Blinding Lights", "Bad Guy"]`
* Merge `pop_playlist` into `rock_playlist` using `.extend()`.
* Calculate the middle index using integer floor division (`len(list) // 2`).
* Use `.insert()` to place `"Stairway to Heaven"` at that exact middle index and print the updated playlist.

In [18]:
rock_playlist = ["Bohemian Rhapsody", "Hotel California"]
pop_playlist = ["Shape of You", "Blinding Lights", "Bad Guy"]

# 1. Extend rock_playlist with pop_playlist
rock_playlist.extend(pop_playlist)

# 2. Calculate dynamic middle index using floor division
mid_index = len(rock_playlist) // 2

# 3. Insert target track at the calculated index
rock_playlist.insert(mid_index, "Stairway to Heaven")

print("Calculated Middle Index:", mid_index)
print("Updated Playlist:", rock_playlist)

Calculated Middle Index: 2
Updated Playlist: ['Bohemian Rhapsody', 'Hotel California', 'Stairway to Heaven', 'Shape of You', 'Blinding Lights', 'Bad Guy']


## **Problem 19 (Thinking-Based / Application)**
### **The Duplicate Detector & Frequency Counter**
A biometric attendance system registers card swipes by ID numbers in the order they occur: `swipes = [101, 102, 101, 103, 104, 101, 102, 105]`.
* Create an empty list `unique_swipes`.
* Loop through each ID in `swipes`. If the ID is not already in `unique_swipes`, add it using `.append()`.
* After building the unique list, iterate through `unique_swipes` and use `.count()` on `swipes` to display how many times each employee swiped their card.

In [19]:
swipes = [101, 102, 101, 103, 104, 101, 102, 105]
unique_swipes = []

# Build unique deduplicated list preserving original order
for swipe_id in swipes:
    if swipe_id not in unique_swipes:
        unique_swipes.append(swipe_id)

# Iterate through unique IDs and count occurrences in original swipes list
for swipe_id in unique_swipes:
    frequency = swipes.count(swipe_id)
    print(f"ID {swipe_id} swiped {frequency} times")

ID 101 swiped 3 times
ID 102 swiped 2 times
ID 103 swiped 1 times
ID 104 swiped 1 times
ID 105 swiped 1 times


## **Problem 20 (Thinking-Based / Application)**
### **The Security Log Trim (Tail Analysis)**
A cloud security server generates system log entries continuously:
`logs = ["LOG1", "LOG2", "LOG3", "LOG4", "LOG5", "LOG6", "LOG7", "LOG8", "LOG9", "LOG10"]`.
* Use negative slicing to extract the last 5 logs into a new variable `recent_logs`.
* Reverse `recent_logs` using the `.reverse()` method.
* Loop through the reversed list and print each log entry prefixed with `"CRITICAL AUDIT: "` using a `for` loop.

In [20]:
logs = ["LOG1", "LOG2", "LOG3", "LOG4", "LOG5", "LOG6", "LOG7", "LOG8", "LOG9", "LOG10"]

# 1. Negative slice to extract tail (last 5 entries)
recent_logs = logs[-5:]

# 2. Reverse list in-place to get reverse chronological order
recent_logs.reverse()

# 3. Print each log with formatted prefix
for log in recent_logs:
    print(f"CRITICAL AUDIT: {log}")

CRITICAL AUDIT: LOG10
CRITICAL AUDIT: LOG9
CRITICAL AUDIT: LOG8
CRITICAL AUDIT: LOG7
CRITICAL AUDIT: LOG6
